language: generic
sudo: required
services: docker
branches:
  only:
    - master
env:
  global:
  - PROJECT_NAME=lpp-frontend
  - PROJECT_VERSION=1.0.11
  - DOCKER_USERNAME=bezpov
  - secure: 5IdsUAIE11VNJs8cChw774lXiHnhOYNh3H4NP/WjfqNtlrFsQb1PO6I2zyKCr11FipvAy4PRaOvHnIs9OMJGTvSL5mOKkcuKinNdUfDJhtI+qMZcQKOHq/qAH39nIPmCipUcW9qslvMMMFm9YIdPJpWdEhb/iMIf8z0WzH7FcgOyQLRKGhjlt9FNLlffegS2S5oKpHXgNb1o2y3z5YD7rs+xyMYfvLC4dXUMRk6iV6SC5xoeKBAmc89hwqvYnIY6mvilyOGcEtZt9up4LvGOuGfhosbJBO2UuQLysmodU/RcJjWjcuxAtxTMF/tyJvbG7MH4gLZt4KG7Ijho7W743SZjgrtFX9MrajGH9TttfhqzN//mKs5UP3VgS21vk21F6oOs/imnUwRChWmROF8hepmaCd+nVnfl/U5yWQ+/OeYofI0OvAhCtQoWBs124l3dyVoNEwDKe3xdfEblZzmcLVVDy7acH0v3ysg8flEmTsTZv0sn3KvVTghxATlbGLRBSfq3yvSTDhfpFWDOexJHZ4Ct5miHQloIEjJ68ontoz+OT00hoJ2pApM71R6UewRxvJae2wLMG3mf7dqo22kAEY8ZpGpbre9/uJ2Et6YECFrUG+1+u29ji1VNTjT5Lul9r/Zm4YA7+EFs6TH/+sIoFd1/xUq19hCtVG5QZsDVX5g=
  - secure: TmNrGALk7svzkPHq1Z8IU44RlIA9oozjqxwaDzd5EVkBfjvl3dT72dtoy/GLcGURJ5eakb9xXURAzh76bmQsquqAwkh4wjBbM6lO8wxL3LsIP4CtgVmCM8aQeux/2LRulcJfNIuQm/YsPQXLz+V3wBcPYiP/sdMVGB2Jmi9oOr6TD+3yoEO5JzjI2pVZXkhsTMmAMSxWJAebXNW/XyA8JrfCpLmsOXVkrGLjPLc6vfFF3I0SYuaN15o2yx8VJUxuXq6ZGXdMCRY4iuKtLpKmu7bwd1xFzYaJQKXDQEbYs1/dqP32AlCZv2ilMxlCsHenm7UPYr8ip3YDjhVvMH1KBdX7rxZIqHz/c5VIPOIifZKu7iDHBx1xCRM1mR8fDhfZh9gs5JHxQ0Vrf64+B7SqvHZ7mcRYDtlHhienDGY+IYDc5s7siou5hztQU51CHKUcGFrUtTZAFdOft9rqjjS6D/B79H2Ked98qizNSASlakTVlhgSSdKhyz+S921BxBIbl+wMpRuZsDZTOxTK7otbtB1y334UcuZAhJi30/daqZ9zT1irzZryV6/HRBcHpkPN+TfIl098v60lhu4YrXVKXLPf8LHWtGlfPl4YAsxruoHGU9VxgGfkjXeXAjNtiL6QF+ewJHLfdq6vsHM6wPNqnA/CjDGstpsk4FxOUvRWN9E=
before_install:
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 google-travis-service-account.json.gpg
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file google-travis-service-account.json
- gcloud config set project massive-boulder-263710
- gcloud container clusters get-credentials lpp --zone us-central1-a --project massive-boulder-263710
- gcloud components install kubectl
- kubectl apply -f ./kubernetes/deployment.yaml