language: generic
sudo: required
services: docker
branches:
  only:
    - master
env:
  global:
  - PROJECT_NAME=lpp-frontend
  - PROJECT_VERSION=1.0.1
  - DOCKER_USERNAME=bezpov
  - secure: 5IdsUAIE11VNJs8cChw774lXiHnhOYNh3H4NP/WjfqNtlrFsQb1PO6I2zyKCr11FipvAy4PRaOvHnIs9OMJGTvSL5mOKkcuKinNdUfDJhtI+qMZcQKOHq/qAH39nIPmCipUcW9qslvMMMFm9YIdPJpWdEhb/iMIf8z0WzH7FcgOyQLRKGhjlt9FNLlffegS2S5oKpHXgNb1o2y3z5YD7rs+xyMYfvLC4dXUMRk6iV6SC5xoeKBAmc89hwqvYnIY6mvilyOGcEtZt9up4LvGOuGfhosbJBO2UuQLysmodU/RcJjWjcuxAtxTMF/tyJvbG7MH4gLZt4KG7Ijho7W743SZjgrtFX9MrajGH9TttfhqzN//mKs5UP3VgS21vk21F6oOs/imnUwRChWmROF8hepmaCd+nVnfl/U5yWQ+/OeYofI0OvAhCtQoWBs124l3dyVoNEwDKe3xdfEblZzmcLVVDy7acH0v3ysg8flEmTsTZv0sn3KvVTghxATlbGLRBSfq3yvSTDhfpFWDOexJHZ4Ct5miHQloIEjJ68ontoz+OT00hoJ2pApM71R6UewRxvJae2wLMG3mf7dqo22kAEY8ZpGpbre9/uJ2Et6YECFrUG+1+u29ji1VNTjT5Lul9r/Zm4YA7+EFs6TH/+sIoFd1/xUq19hCtVG5QZsDVX5g=
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
